# Unsigned Ints:
def read_u8(*args, **kwargs):
    ...
    
def write_u8(*args, **kwargs):
    ...

def read_u16(*args, **kwargs):
    ...
    
def write_u16(*args, **kwargs):
    ...

def read_u32(*args, **kwargs):
    ...
    
def write_u32(*args, **kwargs):
    ...

def read_u64(*args, **kwargs):
    ...
    
def write_u64(*args, **kwargs):
    ...

# Signed Ints:
def read_s8(*args, **kwargs):
    ...
    
def write_s8(*args, **kwargs):
    ...

def read_s16(*args, **kwargs):
    ...
    
def write_s16(*args, **kwargs):
    ...

def read_s32(*args, **kwargs):
    ...
    
def write_s32(*args, **kwargs):
    ...

def read_s64(*args, **kwargs):
    ...
    
def write_s64(*args, **kwargs):
    ...

# Floats:
def read_f32(*args, **kwargs):
    ...
    
def write_f32(*args, **kwargs):
    ...

def read_f64(*args, **kwargs):
    ...
    
def write_f64(*args, **kwargs):
    ...

# Text:
def read_char(*args, **kwargs):
    ...
    
def write_char(*args, **kwargs):
    ...

def read_str(*args, **kwargs):
    ...

def read_str_n(*args, **kwargs):
    ...

def write_str_n(*args, **kwargs):
    ...

def read_byte_str(*args, **kwargs):
    ...

def read_byte_str_n(*args, **kwargs):
    ...

def write_byte_str_n(*args, **kwargs):
    ...

# Memory
def read_bytes_n(*args, **kwargs):
    ...
    
def write_bytes_n(*args, **kwargs):
    ...
    
