#include "repy_utils.hpp"

py::bytes recomp_memcpy_to_py_bytes(uint8_t* rdram, int32_t ptr, uint32_t size, bool reverse) {
    // Initalize the Python Object.
    PyObject* new_bytes = PyBytes_FromStringAndSize(nullptr, size);
    if (new_bytes == NULL) {
        // If there was somehow an error caused by generated by this, throw it here.
        throw py::error_already_set();
    } 

    // Writing directly to the internal buffer:
    char* buf = PyBytes_AS_STRING(new_bytes);
    if (reverse) {
        memcpy_rev_from_recomp(rdram, buf, ptr, size);
    } else {
        memcpy_from_recomp(rdram, buf, ptr, size);
    }
    
    // Convert the raw PyObject* to a pybind11 type.
    return py::reinterpret_steal<py::bytes>(new_bytes);
}

py::bytearray recomp_memcpy_to_py_bytearray(uint8_t* rdram, int32_t ptr, uint32_t size, bool reverse) {
    // Initalize the Python Object.
    PyObject* new_bytearray = PyByteArray_FromStringAndSize(nullptr, size);
    if (new_bytearray == NULL) {
        // If there was somehow an error caused by generated by this, throw it here.
        throw py::error_already_set();
    } 

    // Writing directly to the internal buffer:
    char* buf = PyByteArray_AS_STRING(new_bytearray);
    if (reverse) {
        memcpy_rev_from_recomp(rdram, buf, ptr, size);
    } else {
        memcpy_from_recomp(rdram, buf, ptr, size);
    }

    // Convert the raw PyObject* to a pybind11 type.
    return py::reinterpret_steal<py::bytearray>(new_bytearray);
}